numA = input("enter first number:" )
numB = input("enter second number:" )
num1 = int(numA)
num2 = int(numB)
23
print(f"num1 + num2 = {num1 + num2}")
print(f"num1 - num2 = {num1 - num2}")
print(f"num1 * num2 = {num1 * num2}")
print(f"num1 / num2 = {num1 / num2}")
print(f"num1 % num2 = {num1 % num2}")